[general]
live_config_reload = true

[colors.primary]
background = "0x16000b"
foreground = "0xdddddd"

[colors.search.matches]
background = "0x300030"
foreground = "0x000000"

[cursor]
blink_interval = 450
thickness = 0.35
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 13

[font.italic]
style = "Normal"

[font.normal]
family = "Drafting* Mono Light"
style = "Light Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9
